[toolchain]
anchor = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
early-access = "jg82rRko6Hu1KqZ47RR95Jrq1cfqBhaAPXStseajmfQ"

[programs.devnet]
early-access = "jg82rRko6Hu1KqZ47RR95Jrq1cfqBhaAPXStseajmfQ"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "http://localhost:8899"
cluster = "mainnet"
wallet = "~/.config/solana/haio-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/*"
]
exclude = [
    "programs/pre-registration"
]